name: $(versionnumber)

variables:
  - name: filepathbase
    value: 01-simpletemplatespec/01-simpletemplatespec
  - name: filepathArm
    value: $(filepathbase).json
  - name: templateSpecName
    value: az-tempspec-webapp
  - name: resourcegroupname
    value: sponsor-rg-templatespecs
  - name: location
    value: westeurope
    
trigger:
  - main
  paths:
    include:
    - 01-simpletemplatespe
  
pool:
  vmImage: windows-2019

steps:
- task: AzurePowerShell@5
  displayName: "Check resource group"
  inputs:
    azureSubscription: 'Subscription Sponsorship'
    ScriptType: 'InlineScript'
    Inline: |
      if (!(Get-AzResourceGroup "$(resourcegroupname)" -ErrorAction SilentlyContinue)){ 
          New-AzResourceGroup -Name "$(resourcegroupname)" -Location "$(location)"
      }else{
          Write-Output "The resource group already exists"
      }
    azurePowerShellVersion: 'LatestVersion'
    pwsh: true
- task: AzurePowerShell@5
  displayName: "Deploy template spec"
  inputs:
    azureSubscription: 'Subscription Sponsorship'
    ScriptType: 'InlineScript'
    Inline: |
      New-AzTemplateSpec -Name "$(templateSpecName)" -Version "$(versionnumber)" -ResourceGroupName "$(resourcegroupname)" -Location "$(location)" -TemplateFile "$(System.DefaultWorkingDirectory)/$(filepathArm)"
    azurePowerShellVersion: 'LatestVersion'
    pwsh: true
- task: versioncounter@1
  displayName: "Update version number"
  inputs:
    VersionVariable: 'versionnumber'
    UpdateMinorVersion: true
    MaxValuePatchVersion: '9'
    DevOpsPat: '$(pipeline-pat)'