trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  - name: bicepFolder
    value: "$(Build.Repository.LocalPath)/bicepInstall"
  - name: bicepPath
    value: "$(Build.Repository.LocalPath)/templatespecs/03-biceptemplatespec"
  - name: fileName
    value: "03-biceptemplatespec"
  - name: serviceConnection
    value: "Subscription Sponsorship"
  - name: specName
    value: "az-tempspec-bicepwebapp"
  - name: resourceGroup
    value: "sponsor-rg-templatespecs"
  - name: subscription
    value: "f124b668-7e3d-4b53-ba80-09c364def1f3"

extends:
  template: templates/stages-specs.yml
  parameters:
    bicepPath: '$(bicepPath)'
    bicepFolder: '$(bicepFolder)'
    fileName: '$(fileName)'
    serviceConnection: '$(serviceConnection)'
    specName: '$(specName)'
    resourceGroup: '$(resourceGroup)'
    subscription: '$(subscription)'