name: "Deploy Template Spec"
description: "Composite actions for deploying a template spec."
inputs:
  clientId:
    description: 'Application client ID'
    required: true
  clientSecret:
    description: 'Application client Secret'
    required: true
  tenantId:
    description: 'Application tenant Id'
    required: true
  azureSubscription:
    description: 'Subscription'
    required: true
  specFolder:
    description: 'Specification folder'
    required: true
  specName:
    description: 'Specification name'
    required: true
  resourceGroup:
    description: 'Name of the resource group'
    required: true
  specFileName:
    description: 'The files name of the spec'
    required: true
runs:
  using: "composite"
  steps:
       - uses: actions/download-artifact@v4
         name: Download template spec
         with:
             name: ${{inputs.specName}}
       - uses: actions/download-artifact@v4
         name: Download utility scripts
         with:
             name: ps-${{inputs.specName}}
       - name: Azure Login
         uses: Azure/login@v2
         with:
           client-id: ${{ inputs.clientId }}
           tenant-id: ${{ inputs.tenantId }}
           subscription-id: ${{ inputs.azureSubscription }}
           enable-AzPSSession: true
       - name: Upload Template Spec
         uses: azure/powershell@v2
         with:
           azPSVersion: latest
           inlineScript: |
             $version = .\Get-TemplateSpecVersion.ps1 -TemplateSpecName "${{env.specName}}" -ResourceGroupName "${{inputs.resourceGroup}}"
             Write-Host "Version: $version"
             New-AzTemplateSpec -Name "${{inputs.specName}}" -Version $version -ResourceGroupName "${{inputs.resourceGroup}}" -Location "westeurope" -TemplateFile ".\${{inputs.specFileName}}"