name: TS - Bicep Module Spec
on:
  push:
    paths:
      - 'templatespecs/04-bicepmoduletemplatespec/*'
      - .github/workflows/templatespec-bicepmoduletemplatespec.yml
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  id-token: write

env:
  specName: az-tempspec-bicepmodulestorage
  specfolder: './templatespecs/04-bicepmoduletemplatespec/04-bicepmoduletemplatespec'
  specfilename: 04-bicepmoduletemplatespec.json
  resourcegroup: sponsor-rg-templatespecs
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: bicepbuild
        uses: ./.github/actions/buildbicep
        with:
          specFolder: ${{env.specfolder}}
          specName: ${{env.specName}}
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v4
       - id: deployspec
         uses: ./.github/actions/deploytemplatespec
         with:
           specFolder: ${{env.specfolder}}
           specName: ${{env.specName}}
           resourceGroup: ${{env.resourcegroup}}
           specFileName : ${{env.specfilename}}
           clientId: ${{ secrets.AZURE_CLIENT_ID }}
           clientSecret: ${{ secrets.AZURE_CLIENT_SECRET }}
           tenantId: ${{ secrets.AZURE_TENANT_ID }}
           azureSubscription: f124b668-7e3d-4b53-ba80-09c364def1f3