name: TS - Certified Storage

on:
  push:
    paths:
      - 'templatespecs/05-certifiedstorage/*'
      - .github/workflows/templatespec-certifiedstorage.yml
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  id-token: write

env:
  specName: az-tempspec-certifiedstorage
  specfolder: './templatespecs/05-certifiedstorage/05-storage'
  specfilename: 05-storage.json
  resourcegroup: gaag-rg-specs
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: bicepbuild
        uses: ./.github/actions/buildbicep
        with:
          specFolder: ${{env.specfolder}}
          specName: ${{env.specName}}
  deploy:
    needs: build
    environment: prod
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v4
       - id: deployspec
         uses: ./.github/actions/deploytemplatespec
         with:
           specFolder: ${{env.specfolder}}
           specName: ${{env.specName}}
           resourceGroup: ${{env.resourcegroup}}
           specFileName : ${{env.specfilename}}
           clientId: ${{ secrets.AZURE_CLIENT_ID }}
           tenantId: ${{ secrets.AZURE_TENANT_ID }}
           azureSubscription: ${{ secrets.AZURE_SUBSCRIPTION_ID }}